### ISSUE TITLE
JSONDecodeError on Windows

### ISSUE THREAD

**Issue by ppullion** [apastel/ytmusic-deleter#10]
Microsoft Windows [Version 10.0.19043.1023]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Phill>ytmusic-deleter
Usage: ytmusic-deleter [OPTIONS] COMMAND [ARGS]...

  Perform batch delete operations on your YouTube Music library.

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  delete-all        Executes delete-uploads, remove-library, unlike-all,...
  delete-playlists  Delete all playlists
  delete-uploads    Delete all tracks that you have uploaded to your YT...
  remove-library    Remove all tracks that you have added to your library...
  unlike-all        Reset all Thumbs Up ratings back to neutral

C:\Users\Phill>ytmusic-deleter delete-all
[2021-06-05 17:37:15] Retrieving all uploaded albums...
Traceback (most recent call last):
  File "c:\users\phill\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\phill\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Phill\AppData\Local\Programs\Python\Python39\Scripts\ytmusic-deleter.exe\__main__.py", line 7, in <module>
  File "c:\users\phill\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\phill\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "c:\users\phill\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\phill\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\phill\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\phill\appdata\local\programs\python\python39\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\phill\appdata\local\programs\python\python39\lib\site-packages\ytmusic_deleter\cli.py", line 282, in delete_all
    ctx.invoke(delete_uploads)
  File "c:\users\phill\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\phill\appdata\local\programs\python\python39\lib\site-packages\ytmusic_deleter\cli.py", line 46, in delete_uploads
    (albums_deleted, albums_total) = delete_uploaded_albums(add_to_library)
  File "c:\users\phill\appdata\local\programs\python\python39\lib\site-packages\ytmusic_deleter\cli.py", line 60, in delete_uploaded_albums
    uploaded_albums = youtube_auth.get_library_upload_albums(sys.maxsize)
  File "c:\users\phill\appdata\local\programs\python\python39\lib\site-packages\ytmusicapi\mixins\uploads.py", line 74, in get_library_upload_albums
    response = self._send_request(endpoint, body)
  File "c:\users\phill\appdata\local\programs\python\python39\lib\site-packages\ytmusicapi\ytmusic.py", line 128, in _send_request
    response_text = json.loads(response.text)
  File "c:\users\phill\appdata\local\programs\python\python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "c:\users\phill\appdata\local\programs\python\python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\phill\appdata\local\programs\python\python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by apastel** [comment]
I'm not sure why, but when the program was trying to retrieve all of your uploaded albums, the `ytmusicapi` received a response from YT Music that was not JSON when it was expecting JSON. I'd be curious of two things:

1. If you try again now (2.5 months later) do you still get the same error?
2. If you try one of the other commands that don't deal with uploaded albums (such as `remove-library`, `delete-playlists`, or `unlike-all`) do those ones work?

**Comment by apastel** [comment]
Haven't heard back from you in a few months so I'm closing this as resolved.

**Comment by ppullion** [comment]
sorry, kind of just gave up with it.
Thank you,

Phillip Pullion

In a world where you can be anything......     Be Yourself!
*P* *Please consider the environment before printing this e-mail.*
