### ISSUE TITLE
KeyError: 'playlistId' when trying to remove albums or songs

### ISSUE THREAD

**Issue by ghost** [apastel/ytmusic-deleter#14]
C:\WINDOWS\system32>ytmusic-deleter remove-library
[2021-09-23 12:37:49] Retrieving all library albums...
[2021-09-23 12:37:50] Retrieved 0 albums from your library.
[2021-09-23 12:37:50] Retrieving all singles...
[2021-09-23 12:38:03] Retrieved 1408 singles from your library.
[2021-09-23 12:38:03] Processing album: Unknown Artist - Christmas in Tahoe (Deluxe Edition)
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python39\Scripts\ytmusic-deleter.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python39\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Python39\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Python39\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\ytmusic_deleter\cli.py", line 189, in remove_library
    albums_removed += remove_library_albums_by_song(album_unique_songs, progress_bar)
  File "C:\Program Files\Python39\lib\site-packages\ytmusic_deleter\cli.py", line 206, in remove_library_albums_by_song
    if remove_album(song["album"]["id"]):
  File "C:\Program Files\Python39\lib\site-packages\ytmusic_deleter\cli.py", line 222, in remove_album
    response = youtube_auth.rate_playlist(album["playlistId"], const.INDIFFERENT)
KeyError: 'playlistId'

Thanks for this awesome tool and any help you can provide.

**Comment by apastel** [comment]
I'm getting the same error. Something must have changed in the YouTube Music backend. I will look into it.
