### ISSUE TITLE
unlike-all error logged

### ISSUE THREAD

**Issue by jdtemple** [apastel/ytmusic-deleter#16]
It looks like the code choked on an unexpected character in a song title that is using a right single quotation mark, instead of the usual apostrophe character. Here's error log:

```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\x92' in position 63: character maps to <undefined>
Call stack:
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\Scripts\ytmusic-deleter.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\site-packages\ytmusic_deleter\cli.py", line 282, in unlike_all
    logging.info(f"Processing track: {artist} - {title}")
Message: "Processing track: Propagandhi - Fedallah'\x92s Hearse"
Arguments: ()
[2022-04-09 09:16:16] Processing track: Propagandhi - Fedallah's Hearse
[2022-04-09 09:16:16]   Removed track from Likes.
```

**Comment by jdtemple** [comment]
Here is the song with the wonky character in the title:

![image](https://user-images.githubusercontent.com/2552341/162578359-66576a9a-c8bd-4959-af55-e524637e8957.png)

**Comment by apastel** [comment]
Seems like it's choking on the actual logging statement. Interestingly enough, it still prints the logging statement afterwards. 

Hmm, it looks like it's not giving me an issue for some reason.
```
(.venv) apastel@Alex-Win10:~/dev/ytmusic-deleter$ ytmusic-deleter unlike-all
[2022-04-09 11:49:59] Retrieving all your liked songs...
[2022-04-09 11:50:00]   Retrieved 3 liked songs.
[2022-04-09 11:50:00] Begin unliking songs...
[2022-04-09 11:50:00] Processing track: Propagandhi - Bringer of Greater Things
[2022-04-09 11:50:00]   Removed track from Likes.
[2022-04-09 11:50:00] Processing track: Propagandhi - Cut into the Earth
[2022-04-09 11:50:00]   Removed track from Likes.
[2022-04-09 11:50:00] Processing track: Propagandhi - Fedallah's Hearse
[2022-04-09 11:50:00]   Removed track from Likes.
[2022-04-09 11:50:00] Finished unliking all songs.

Songs Unliked 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00, 5.51 songs/s]
(.venv) apastel@Alex-Win10:~/dev/ytmusic-deleter$ python --version
Python 3.10.4
```

Did it halt the whole program for you or did it still continue on and remove the remaining likes, including that one?

**Comment by jdtemple** [comment]
It did not halt the program, it continued on and removed the remaining likes.

I'm not 100% sure if worked on that particular track. I was in there looking at it and removed it with the YTM UI as I reported the issue.

**Comment by jdtemple** [comment]
One thing of note, there are two versions of that track. Mine was the Explicit one. The censored one does not have the bad character in the title.

**Comment by apastel** [comment]
Ok, I ran it in Windows and saw the error. I thought maybe it's because the default encoding in Windows is cp1252 instead of utf-8 and can't encode/decode that character but I set logging config to utf-8 and that didn't resolve it. Anyway, at least I can replicate it and I'll look into it (although somewhat low pri because it still unlikes the song and continues on). Thanks for the report!

**Comment by jdtemple** [comment]
Yeah, it's probably not a big deal. If I wasn't actively watching the console white it ran, I'd have probably never noticed.
