### ISSUE TITLE
unhandled exception in sort_playlist

### ISSUE THREAD

**Issue by copolii** [apastel/ytmusic-deleter#17]
I've tried renaming the playlist to remove spaces and special characters. Will play around with the code to see if I can get a fix. I'm not a Python guy so my PR may need fixing up.

Traceback (most recent call last):
  File "ytmusic_deleter\cli.py", line 484, in <module>
  File "click\core.py", line 1130, in __call__
  File "click\core.py", line 1055, in main
  File "click\core.py", line 1657, in invoke
  File "click\core.py", line 1404, in invoke
  File "click\core.py", line 760, in invoke
  File "click\decorators.py", line 26, in new_func
  File "ytmusic_deleter\cli.py", line 428, in sort_playlist
  File "ytmusic_deleter\cli.py", line 432, in <lambda>
TypeError: 'NoneType' object is not subscriptable
[26072] Failed to execute script 'cli' due to unhandled exception!

**Comment by apastel** [comment]
I saw this and your PR when you posted it a week ago but then I forgot about it! (Been busy moving.) I'll take another look and test it out soon.

**Comment by copolii** [comment]
No problem. It worked for my use case, but there may still be other cases that give it trouble.

**Comment by apastel** [comment]
Hey I just realized...this means people are actually using the sort-playlist function. Radical!

**Comment by copolii** [comment]
I came for the "delete uploads" function and stayed for the "sort playlist" 😉

**Comment by yeltommo** [comment]
I'm a total newbie to Github, so excuse this totally newbie issue. I got stuck on step 1 because I can't find any Releases area....
