### ISSUE TITLE
FileNotFoundError: ANSI64.dll

### ISSUE THREAD

**Issue by oMyqMQ0I70mnbnUk** [apastel/ytmusic-deleter#21]
"ytmusic-deleter-1.4.0.exe"
NotADirectoryError: [WinError 267] The directory name is invalid
Traceback (most recent call last):
  File "PyInstaller\loader\pyimod04_ctypes.py", line 77, in __init__
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'C:\Users\ADMINI~1\AppData\Local\Temp\_MEI1653082\ansicon\ANSI64.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "ytmusic_deleter\cli.py", line 15, in <module>
  File "enlighten\manager.py", line 55, in get_manager
  File "enlighten\_manager.py", line 70, in __init__
  File "enlighten\_basemanager.py", line 74, in __init__
  File "blessed\terminal.py", line 170, in __init__
  File "jinxed\win32.py", line 337, in get_term
  File "ansicon\__init__.py", line 52, in load
  File "PyInstaller\loader\pyimod04_ctypes.py", line 79, in __init__
pyimod04_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\_MEI1653082\\ansicon\\ANSI64.dll'. Most likely this dynlib/dll was not found when the application was frozen.
[166384] Failed to execute script 'cli' due to unhandled exception!

**Comment by apastel** [comment]
I apologize, I don't remember getting an email notification for this Issue at all, and I'm usually pretty vigilant about checking my GitHub notification emails!
I would first give the 1.4.1 exe a try (instead of 1.4.0) and if the issue still persists on that version, I might be able to fix it in a 1.4.2 release.

FYI (not that it matters but...) the `NotADirectoryError` is unrelated -- it's the `FileNotFoundError` causing the problem.
