### ISSUE TITLE
IndexError: List Index out of Range

### ISSUE THREAD

**Issue by LateNightMayhem** [apastel/ytmusic-deleter#23]
Hi All,
I am attempting to switch back to Android from iOS. As a result, I am trying to delete and re-sync my YouTube Music library (there are tons of metadata issues, duplicates and etc). When I attempt to run the script, this is the error I get (I have changed my username of course for OpSec Reasons):

  Traceback (most recent call last):
  File "C:\Users\xxxxxx\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\xxxxxx\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxxxxx\anaconda3\Scripts\ytmusic-deleter.exe\__main__.py", line 7, in <module>
  File "C:\Users\xxxxxx\anaconda3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\xxxxxx\anaconda3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\xxxxxx\anaconda3\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\xxxxxx\anaconda3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\xxxxxx\anaconda3\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\xxxxxx\anaconda3\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\xxxxxx\anaconda3\lib\site-packages\ytmusic_deleter\cli.py", line 82, in delete_uploads
    (albums_deleted, albums_total) = delete_uploaded_albums(ctx, add_to_library)
  File "C:\Users\xxxxxx\anaconda3\lib\site-packages\ytmusic_deleter\cli.py", line 109, in delete_uploaded_albums
    album["artists"][0]["name"]
IndexError: list index out of range

what am I doing wrong? I will gladly buy a beer to help me fix this. 
Thanks

**Comment by apastel** [comment]
Please help me out with the following bits of info:

- The command you're running
- The version of ytmusic-deleter you're running (type `ytmusic-deleter --version`)

**Comment by LateNightMayhem** [comment]
The command is ytmusic-deleter delete-all (delete-uploads also doesn't work)
I'm running version 1.5.2

**Comment by apastel** [comment]
Yeah it's never usually a Python issue, it's almost always either an issue with a specific album or song, or it's an issue with Google  changing how their API works and the rest of us constantly having to play catch-up. 

Before I try to replicate it let me ask, does it seem to start deleting stuff and then fails partway into it? Or does this error appear as soon as you enter the command? Provide the full output if there's anything else that appears above this.

**Comment by LateNightMayhem** [comment]
Honestly, I think they changed their API (again, smh). 

It does not appear to delete things at all. This message will appears after the "Retrieving all uploaded albums..." message does which ultimately fails and never takes place. 

Example (from Python):
[2023-01-17 18:37:56] Looking for C:\Users\xxxxxx\headers_auth.json"
[2023-01-17 18:37:56] Found C:\Users\xxxxxx\headers_auth.json"
[2023-01-17 18:37:56] Retrieving all uploaded albums...

and then that's when the proceeding messages above appears after a very short time.

**Comment by apastel** [comment]
It's happening for me as well, it's specific to `delete-uploads`. Not only does Google change their API but I have to keep up with changes to the `ytmusicapi` project that my tool depends on. Thanks for pointing it out. Probably a small code change, will fix ASAP.

**Comment by apastel** [comment]
I just published release 1.5.3 which should fix the issue.
Update to it by running `pip install --upgrade ytmusic-deleter`

So I think it was happening because often when we upload stuff to YTMusic, it doesn't actually assign an "Artist" like we think it should. So, coincidentally (but not that coincidentally) when I was testing it, I too had an uploaded album where there was no Artist. YTMusic is really bad at interpreting your .mp3 metadata and putting the correct artist on the album. So, my code was blowing up when it came across an album where the `"artists"` field was an empty list `[]`. I think previously this used to work because the `artists` field would just not exist at all. Now my code handles both cases.

Anyway, hopefully it works now.

**Comment by LateNightMayhem** [comment]
Buying you a *few* beers. Thanks so much. Issue appears to be fixed!

**Comment by apastel** [comment]
Glad I could help. (btw if you bought me any beers, I didn't get them 😄)
