### ISSUE TITLE
Error executing the .exe and the script as well

### ISSUE THREAD

**Issue by Devroot1337** [apastel/ytmusic-deleter#24]
Hi, I get the following errors, albums i deleted manually but have like 10k uploaded singles i want to delete.. If you can fix this I will be very happy. 

Showing confirmation dialog
Executing process: C:\Windows\System32\ytmusic-deleter-1.5.4.exe ['-l', 'C:\\Users\\Admin\\AppData\\Roaming\\YTMusic Deleter', '-c', 'C:\\Users\\Admin\\AppData\\Roaming\\YTMusic Deleter', '-p', 'delete-uploads']
State changed: Starting
State changed: Running
FileNotFoundError: [WinError 2] Het systeem kan het opgegeven bestand niet vinden
[2023-02-28 19:45:15] Looking for C:\Users\Admin\AppData\Roaming\YTMusic Deleter\headers_auth.json"
[2023-02-28 19:45:15] Found C:\Users\Admin\AppData\Roaming\YTMusic Deleter\headers_auth.json"
[2023-02-28 19:45:15] Retrieving all uploaded albums...
[2023-02-28 19:45:15] Deleted 0 out of 0 uploaded albums.
[2023-02-28 19:45:15] Retrieving all uploaded singles...
Traceback (most recent call last):
  File "ytmusic_deleter\cli.py", line 495, in <module>
  File "click\core.py", line 1130, in __call__
  File "click\core.py", line 1055, in main
  File "click\core.py", line 1657, in invoke
  File "click\core.py", line 1404, in invoke
  File "click\core.py", line 760, in invoke
  File "click\decorators.py", line 26, in new_func
  File "ytmusic_deleter\cli.py", line 89, in delete_uploads
  File "ytmusic_deleter\cli.py", line 163, in delete_uploaded_singles
KeyError: 'artist'
[33496] Failed to execute script 'cli' due to unhandled exception!
State changed: Not running
Process finished.

**Comment by apastel** [comment]
I believe I have found and fixed the issue. I published a new release (1.5.6), go ahead and download & install it. It will automatically overwrite your previous version. Let me know if it works!
https://github.com/apastel/ytmusic-deleter/releases/tag/1.5.6

**Comment by Devroot1337** [comment]
Cheers m8,

It worked! Another 3 beers to drink on the success of not clicking and the
evilness of google ;)

With regards,

JP

Op wo 1 mrt 2023 om 06:10 schreef Alex Pastel ***@***.***>:

**Comment by apastel** [comment]
Thanks so much! So glad it helped.
By the way, with all the 10021 singles it deleted, I'm surprised that you never reached Google's maximum number of API requests and it started timing out and rejecting the requests. Did that ever happen? Did you have to take a break in between deletions or were you able to do them all in one batch?

**Comment by Devroot1337** [comment]
Hi, no it only stopped once halfway I think, but that was because my pc
went into sleep saving mode i guess, but could also be a limit it reached.
Thanks again for the software.

With regards,

Jp

Op wo 1 mrt. 2023 17:42 schreef Alex Pastel ***@***.***>:
