### ISSUE TITLE
Sorting Playlist throws TypeError: 'NoneType' 

### ISSUE THREAD

**Issue by Er4twXz** [apastel/ytmusic-deleter#55]
State changed: Running
[2024-07-05 08:13:23] Attempting authentication with: C:\Users\XXXX\AppData\Roaming\YTMusic_Deleter\oauth.json
[2024-07-05 08:13:23] Authenticated with: C:\Users\XXXX\AppData\Roaming\YTMusic_Deleter\oauth.json"
[2024-07-05 08:13:24] Logged in as 'XXXXX'
[2024-07-05 08:13:25] Processing playlist: Cosden Solutions
Traceback (most recent call last):
  File "cli.py", line 508, in <module>
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1688, in invoke
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "click\decorators.py", line 33, in new_func
  File "cli.py", line 404, in sort_playlist
TypeError: 'NoneType' object is not subscriptable
[11360] Failed to execute script 'cli' due to unhandled exception!
State changed: Not running
Process finished.

seems to be similar to https://github.com/apastel/ytmusic-deleter/issues/17

**Comment by apastel** [comment]
Hi, sorry just saw this, been on vacation since you opened the issue. You may be able to get around it by turning off debug logging in the File -> Preferences menu, but either way I should be able to fix it when I'm back tomorrow evening. Sorry for the delay.

**Comment by apastel** [comment]
This should be fixed in the latest 2.4.4. release. Give it a try: download the latest release and install it -- it will overwrite your current version. It was likely due to songs that did not have any artist metadata. Those songs will be sorted to the end of the playlist. Let me know if it seems like it's putting songs with known artist names at the end of the playlist incorrectly.
