### ISSUE TITLE
Cannot open the application with KeyError: 'access_token'

### ISSUE THREAD

**Issue by syatibiafnan** [apastel/ytmusic-deleter#56]
Traceback (most recent call last):
  File "main.py", line 481, in <module>
  File "main.py", line 456, in run
  File "main.py", line 431, in window
  File "main.py", line 133, in __init__
  File "main.py", line 201, in update_buttons
  File "main.py", line 176, in is_signed_in
  File "ytmusicapi\mixins\library.py", line 426, in get_account_info
  File "ytmusicapi\ytmusic.py", line 233, in _send_request
  File "ytmusicapi\ytmusic.py", line 218, in headers
  File "ytmusicapi\auth\oauth\token.py", line 43, in as_auth
  File "ytmusicapi\auth\oauth\token.py", line 97, in __getattribute__
  File "ytmusicapi\auth\oauth\token.py", line 63, in update
KeyError: 'access_token'

I made a mistake by unauthorizing ytmusic-deleter through Google account settings rather than the application itself. Any help or information in resolving this issue would be much appreciated.

**Comment by syatibiafnan** [comment]
I found the oauth.json directory and deleted it right away to ensure that the application wrote another json file. Thank you nonetheless.
