### ISSUE TITLE
0 uploads retrieved

### ISSUE THREAD

**Issue by ultimatefrisbeegeek** [apastel/ytmusic-deleter#69]
Hello,

I have been trying to use this app to delete my [YouTube Music] library to start over anew, but every time I try, it says that nothing was deleted, despite the fact I have uploaded content to delete... As a note, I have already authenticated my account to Google, so I'm signed in. I would hate to have to delete items one at a time, as that would take a lot of time... Also, I've tried the commands multiple times, but they keep spitting out that nothing was deleted. Would you have an idea as to what to do next? I'm stumped...

Thanks,
ultimatefrisbeegeek

**Comment by apastel** [comment]
Hi, yeah I can definitely help you but I'll need more specific info. Firstly, can you enable verbose logging from the `File -> Preferences` menu in the app. Then paste the entire log here.

**Comment by ultimatefrisbeegeek** [comment]
Click the 'Sign In' button to connect to your account.
GUI version: 2.5.1
CLI path: C:\Program Files (x86)\YTMusic_Deleter\_internal\ytmusic-deleter.EXE
CLI version: ytmusic-deleter, version 2.5.1
Showing login prompt.
Successfully signed in.
Signed in as [me]
Delete All clicked.
Showing confirmation dialog
Delete All clicked.
Showing confirmation dialog
Executing process: [...]
State changed: Starting
State changed: Running
[2024-08-19 23:31:29] Attempting authentication with: [...]
[2024-08-19 23:31:29] Authenticated with: [...]
[2024-08-19 23:31:29] Starting new HTTPS connection (1): music.youtube.com:443
[2024-08-19 23:31:31] https://music.youtube.com:443 "POST /youtubei/v1/account/account_menu?alt=json HTTP/1.1" 200 None
[2024-08-19 23:31:31] Logged in as [me]
[2024-08-19 23:31:31] Retrieving all uploaded songs...
[2024-08-19 23:31:31] https://music.youtube.com:443 "GET / HTTP/1.1" 200 None
[2024-08-19 23:31:31] https://music.youtube.com:443 "POST /youtubei/v1/browse?alt=json HTTP/1.1" 200 None
[2024-08-19 23:31:31] **No uploaded songs were found.**
[2024-08-19 23:31:31] Deleted 0 out of 0 uploaded albums (or songs).
[2024-08-19 23:31:31] Retrieving all library albums...
[2024-08-19 23:31:32] https://music.youtube.com:443 "POST /youtubei/v1/browse?alt=json HTTP/1.1" 200 None
[2024-08-19 23:31:32] Retrieved 0 albums from your library.
[2024-08-19 23:31:32] Retrieving all songs...
[2024-08-19 23:31:32] https://music.youtube.com:443 "POST /youtubei/v1/browse?alt=json HTTP/1.1" 200 None
[2024-08-19 23:31:32] Retrieved 0 songs from your library.
[2024-08-19 23:31:32] Retreiving all podcasts...
[2024-08-19 23:31:32] https://music.youtube.com:443 "POST /youtubei/v1/browse?alt=json HTTP/1.1" 200 None
[2024-08-19 23:31:32] Retrieved 0 podcasts from your library.
[2024-08-19 23:31:32] Removed 0 out of 0 podcasts from your library.
[2024-08-19 23:31:32] Removed 0 out of 0 albums, songs, and podcasts from your library.
[2024-08-19 23:31:32] Retrieving all your playlists...
[2024-08-19 23:31:32] https://music.youtube.com:443 "POST /youtubei/v1/browse?alt=json HTTP/1.1" 200 None
[2024-08-19 23:31:32] 	Retrieved 1 playlists.
[2024-08-19 23:31:32] Begin deleting playlists...
[2024-08-19 23:31:32] Processing playlist: Episodes for Later
[2024-08-19 23:31:32] https://music.youtube.com:443 "POST /youtubei/v1/playlist/delete?alt=json HTTP/1.1" 400 None
[2024-08-19 23:31:32] 	Could not delete playlist 'Episodes for Later'. You might not have permission to delete it.
[2024-08-19 23:31:32] Total complete: 100%
[2024-08-19 23:31:32] Deleted 0 out of 1 playlists from your library.
[2024-08-19 23:31:32] Retrieving all your liked songs...
[2024-08-19 23:31:32] https://music.youtube.com:443 "POST /youtubei/v1/browse?alt=json HTTP/1.1" 200 None
[2024-08-19 23:31:32] 	Retrieved 0 liked songs.
[2024-08-19 23:31:32] Begin unliking songs...
[2024-08-19 23:31:32] Finished unliking 0 out of 0 songs.
[2024-08-19 23:31:32] Begin deleting history...
[2024-08-19 23:31:32] https://music.youtube.com:443 "POST /youtubei/v1/browse?alt=json HTTP/1.1" 200 None
[2024-08-19 23:31:32] {'text': 'Turn on your YouTube watch history to keep personalized music up to date.'}
Traceback (most recent call last):
  File "cli.py", line 313, in delete_history
  File "ytmusicapi\mixins\library.py", line 300, in get_history
Exception: {'text': 'Turn on your YouTube watch history to keep personalized music up to date.'}
[2024-08-19 23:31:32] Deleted 0 history items.
State changed: Not running
Process finished.

(Please note that some lines were omitted to keep my name out of this post and the path is also omitted for reasons where it also had my name). Thank you for your help and please let me know if anything else is needed.

**Comment by apastel** [comment]
Thanks for sending that.

Just so that I can isolate whether it's an issue with retrieving uploads or retrieving library songs in general, do you have any library songs? That is, songs that you have clicked "Save to library" on and that would show up here under "Library" (as opposed to Uploads)
![image](https://github.com/user-attachments/assets/dcb70c05-e547-47a0-9dcd-7bb736788a89)

In any case, it's likely not an issue with this particular tool but rather the [ytmusicapi](https://github.com/sigma67/ytmusicapi) that this tool uses to interact with your YTM library. Google is constantly making changes to the API and testing changes by region or by a random selection of users, so the `ytmusicapi` has to make frequent adjustments. In the new 1.8.0 version of ytmusicapi, they changed how upload retrieval works, and if you don't see a Downloads button in the web interface (like in that screenshot above) then it won't find any uploads (bug reported [here](https://github.com/sigma67/ytmusicapi/issues/640)).

But I haven't upgraded this tool to use ytmusicapi-1.8.0 yet for that exact reason, so this is unexpected that it would be happening to someone already. That's why I want to know if it's happening for just your uploads or for your library songs as well. Can you try adding some songs to your library from within YTMusic and clicking "Remove Library" and seeing if it deletes those?

**Comment by apastel** [comment]
Alright, I just tested this on my personal YTM account which **does** have a Downloads button in the web interface, and it was not able to find any uploads for me either. I need to make a release of ytmusic-deleter that supports people who do AND do not have a Downloads button, since the ytmusicapi currently only supports the former. Stay tuned for a new release and thank you for bringing this to my attention.

**Comment by apastel** [comment]
Ok, this latest release should fix it for you (the upload issue, at least). This fixes upload retrieval for users who have YTM Premium (instead of the free version).

https://github.com/apastel/ytmusic-deleter/releases

**Comment by ultimatefrisbeegeek** [comment]
Hey, all right @apastel! This was also tested and works for me. Thanks for your help and the time you put into this!

**Comment by ultimatefrisbeegeek** [comment]
Issue resolved with this new release. Thanks again!
