### ISSUE TITLE
Unable to access the service.

### ISSUE THREAD

**Issue by shieldbearer** [apastel/ytmusic-deleter#73]
When lauching the app appear this error:
Failed to execute script "main" due to unhandled exception: "access_token"

Traceback (most recent call last):
  File "main.py", line 483, in <module>
  File "main.py", line 458, in run
  File "main.py", line 433, in window
  File "main.py", line 134, in __init__
  File "main.py", line 203, in update_buttons
  File "main.py", line 178, in is_signed_in
  File "ytmusicapi\mixins\library.py", line 427, in get_account_info
  File "ytmusicapi\ytmusic.py", line 234, in _send_request
  File "ytmusicapi\ytmusic.py", line 219, in headers
  File "ytmusicapi\auth\oauth\token.py", line 43, in as_auth
  File "ytmusicapi\auth\oauth\token.py", line 97, in __getattribute__
  File "ytmusicapi\auth\oauth\token.py", line 63, in update
KeyError: 'access_token'

**Comment by apastel** [comment]
Does this happen when launching the app and using the "Sign In" button to sign in? Or does this happen immediately upon opening the app for the first time?

**Comment by shieldbearer** [comment]
Hello. Happens while opening the app for the first time without ever signing in. Reinstalled and installed different versions and problem persist.

**Comment by apastel** [comment]
Weird. So it's trying to get your account info even though you haven't signed in yet.

I think there may be some kind of leftover authentication file in your user data, which does not get cleared when you uninstall/re-install the app. The only way to clear it is to find it in your APP_DATA directory and delete it. On Windows, this is typically `C:\Users\<username>\AppData\Roaming\YTMusic_Deleter`. Just delete the whole `YTMusic_Deleter` directory in there. No need to uninstall/re-install, just re-launch the app after doing that and see what happens.

**Comment by shieldbearer** [comment]
Yeah, that fixed it. Thanks for your time :)
